---
title: "Quarto 1"
format: html
author: Astri Cahyani
---

```{r}
library(tidyverse)
library(palmerpenguins)
```


```{r}
#| warning: false
#| message: false
#| fig-alt: "Scatter plot of flipper length vs body mass for three penguin species: Adelie (orange), Chinstrap (purple), and Gentoo (blue-green). There is a positive correlation between flipper length and body mass, with Gentoo penguins being noticeably larger."

penguins %>%
  filter(!is.na(flipper_length_mm), !is.na(body_mass_g), !is.na(species)) %>%
  ggplot(aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = species),
             size = 3, alpha = 0.8) +
  scale_color_manual(values = c("Adelie" = "darkorange", "Chinstrap" = "purple", "Gentoo" = "cyan4")) +
  labs(title = "Penguin Size in Palmer Station Land",
       subtitle = "Flipper length and body mass for Adelie, Chinstrap, and Gentoo Penguins",
       x = "Flipper length (mm)",
       y = "Body mass (g)",
       color = "Penguin species",
       shape = "Penguin species") +
  theme_minimal() +
  theme(
    legend.position = c(0.2, 0.85),
    legend.background = element_rect(fill = "white", color = NA),
    plot.title.position = "plot",
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(size = 11, color = "grey30"),
    panel.grid.minor = element_blank()
  )
```

